---
kind: pipeline
name: icekramel CI

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
  - name: build
    image: archlinux:base-devel
    environment:
      patched_glibc: glibc-linux4-2.33-5-x86_64.pkg.tar.zst
      KBUILD_BUILD_USER: misaka
      KBUILD_BUILD_HOST: tp-workstation
    commands:
      - curl -LO "https://repo.archlinuxcn.org/x86_64/$patched_glibc" && bsdtar -C / -xvf "$patched_glibc"
      - cd /drone/src
      - pacman -Sy bc cpio libyaml lib32-gcc-libs aarch64-linux-gnu-gcc arm-none-eabi-gcc --noconfirm
      - bash ./build.sh upload
